name: ci
on:
  push: ~
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 13.x, 14.x ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Install Dependencies"
        run: npm install

      - name: "Test"
        run: npm run test:prod

      - name: "Build"
        run: npm run build

      - name: "Report coverage"
        run: npm run report-coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
  release:
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    needs: build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Git User config"
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"

      - name: "Install Dependencies"
        run: npm install

      - name: "Build"
        run: npm run build

      - name: "Deploy docs"
        run: npm run deploy-docs

      - name: "Semantic Release"
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
