name: ci
on:
  push: ~
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x, 18.x, 19.x ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Install Dependencies"
        run: yarn

      - name: "Test"
        run: yarn test:prod

      - name: "Build"
        run: yarn build

      - name: "Report coverage"
        run: yarn report-coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
  release:
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    needs: build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Git User config"
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"

      - name: "Install Dependencies"
        run: yarn

      - name: "Build"
        run: yarn build

      - name: "Deploy docs"
        run: yarn deploy-docs

      - name: "Semantic Release"
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
